/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseIdIndexRouteImport } from './routes/course/$id/index'
import { Route as LayoutTeachersIndexRouteImport } from './routes/_layout/teachers/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutProgressIndexRouteImport } from './routes/_layout/progress/index'
import { Route as LayoutPlanIndexRouteImport } from './routes/_layout/plan/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutCoursesIndexRouteImport } from './routes/_layout/courses/index'
import { Route as LayoutCertificationsIndexRouteImport } from './routes/_layout/certifications/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdIndexRoute = CourseIdIndexRouteImport.update({
  id: '/course/$id/',
  path: '/course/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeachersIndexRoute = LayoutTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProgressIndexRoute = LayoutProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlanIndexRoute = LayoutPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesIndexRoute = LayoutCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCertificationsIndexRoute =
  LayoutCertificationsIndexRouteImport.update({
    id: '/certifications/',
    path: '/certifications/',
    getParentRoute: () => LayoutRoute,
  } as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/_auth/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/certifications/': typeof LayoutCertificationsIndexRoute
  '/courses/': typeof LayoutCoursesIndexRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/plan/': typeof LayoutPlanIndexRoute
  '/progress/': typeof LayoutProgressIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/teachers/': typeof LayoutTeachersIndexRoute
  '/course/$id/': typeof CourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/certifications': typeof LayoutCertificationsIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/plan': typeof LayoutPlanIndexRoute
  '/progress': typeof LayoutProgressIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/teachers': typeof LayoutTeachersIndexRoute
  '/course/$id': typeof CourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_layout/certifications/': typeof LayoutCertificationsIndexRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/plan/': typeof LayoutPlanIndexRoute
  '/_layout/progress/': typeof LayoutProgressIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/teachers/': typeof LayoutTeachersIndexRoute
  '/course/$id/': typeof CourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/register/'
    | '/certifications/'
    | '/courses/'
    | '/dashboard/'
    | '/plan/'
    | '/progress/'
    | '/settings/'
    | '/teachers/'
    | '/course/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/certifications'
    | '/courses'
    | '/dashboard'
    | '/plan'
    | '/progress'
    | '/settings'
    | '/teachers'
    | '/course/$id'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_layout/certifications/'
    | '/_layout/courses/'
    | '/_layout/dashboard/'
    | '/_layout/plan/'
    | '/_layout/progress/'
    | '/_layout/settings/'
    | '/_layout/teachers/'
    | '/course/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  CourseIdIndexRoute: typeof CourseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id/': {
      id: '/course/$id/'
      path: '/course/$id'
      fullPath: '/course/$id/'
      preLoaderRoute: typeof CourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/teachers/': {
      id: '/_layout/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof LayoutTeachersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/progress/': {
      id: '/_layout/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof LayoutProgressIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plan/': {
      id: '/_layout/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof LayoutPlanIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutCoursesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/certifications/': {
      id: '/_layout/certifications/'
      path: '/certifications'
      fullPath: '/certifications/'
      preLoaderRoute: typeof LayoutCertificationsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutCertificationsIndexRoute: typeof LayoutCertificationsIndexRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutPlanIndexRoute: typeof LayoutPlanIndexRoute
  LayoutProgressIndexRoute: typeof LayoutProgressIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutTeachersIndexRoute: typeof LayoutTeachersIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCertificationsIndexRoute: LayoutCertificationsIndexRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutPlanIndexRoute: LayoutPlanIndexRoute,
  LayoutProgressIndexRoute: LayoutProgressIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutTeachersIndexRoute: LayoutTeachersIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  CourseIdIndexRoute: CourseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
